
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A voice announcement AI agent.
 *
 * - announceTicket - A function that handles the voice announcement generation.
 * - AnnounceTicketInput - The input type for the announceTicket function.
 * - AnnounceTicketOutput - The return type for the announceTicket function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnnounceTicketInputSchema = z.object({
  ticketNumber: z.string().describe('The ticket number to announce.'),
  counterDetails: z.string().describe('The counter details to announce, e.g., counter number or name.'),
});
export type AnnounceTicketInput = z.infer<typeof AnnounceTicketInputSchema>;

const AnnounceTicketOutputSchema = z.object({
  announcementText: z.string().describe('The generated announcement text.'),
});
export type AnnounceTicketOutput = z.infer<typeof AnnounceTicketOutputSchema>;

export async function announceTicket(input: AnnounceTicketInput): Promise<AnnounceTicketOutput> {
  return announceTicketFlow(input);
}

const prompt = ai.definePrompt({
  name: 'announceTicketPrompt',
  input: {schema: AnnounceTicketInputSchema},
  output: {schema: AnnounceTicketOutputSchema},
  prompt: `You are a voice announcement system for a local queue.
  Generate an announcement for the following ticket number and counter details.
  Ticket Number: {{{ticketNumber}}}
  Counter Details: {{{counterDetails}}}
  The announcement should be clear and concise, suitable for a public announcement system.
  `,
});

const announceTicketFlow = ai.defineFlow(
  {
    name: 'announceTicketFlow',
    inputSchema: AnnounceTicketInputSchema,
    outputSchema: AnnounceTicketOutputSchema,
  },
  async input => {
    const response = await prompt(input);
    const structuredOutput = response.output;

    if (!structuredOutput || typeof structuredOutput.announcementText !== 'string' || structuredOutput.announcementText.trim() === '') {
      console.error('Genkit flow "announceTicketFlow" did not receive valid announcementText from the prompt. Output:', structuredOutput);
      throw new Error('AI failed to generate valid announcement text.');
    }
    return structuredOutput;
  }
);

